#!/usr/bin/env python3
"""Generate exact decimal midpoint regressions using Python integer arithmetic."""
from pathlib import Path


def generate() -> str:
    lines = ['// Generated by script/gen_midpoint_tests.py; do not edit.',
             'struct midpoint_case { bool is_double; const char* text; std::uint64_t expected; bool range_error; };',
             'static constexpr midpoint_case midpoint_cases[] = {']
    for precision, bias, fields in [(52, 1023, [0, 1, 2, 20, 500, 1000, 1023, 1024, 1500, 2045, 2046]),
                                     (23, 127, [0, 1, 2, 20, 63, 100, 126, 127, 128, 200, 253, 254])]:
        hidden = 1 << precision
        infinity = (2 * bias + 1) << precision
        for field in fields:
            for fraction in [0, 1, hidden - 1]:
                lower = (field << precision) | fraction
                coefficient = 2 * (fraction + (hidden if field else 0)) + 1
                power = (field or 1) - bias - precision - 1
                if power >= 0:
                    coefficient <<= power
                    scale = 0
                else:
                    coefficient *= 5 ** -power
                    scale = power
                # Place perturbations four decimal places below the exact midpoint.
                coefficient *= 10000
                scale -= 4
                for delta in [-1, 0, 1]:
                    expected = lower if delta < 0 else lower + 1 if delta > 0 else lower + (lower & 1)
                    text = f'{coefficient + delta}e{scale}'
                    lines.append(f'  {{ {str(precision == 52).lower()}, "{text}", 0x{expected:x}ULL, '
                                 f'{str(expected in (0, infinity)).lower()} }},')
    lines.append('};')
    return '\n'.join(lines) + '\n'


if __name__ == '__main__':
    destination = Path(__file__).resolve().parents[1] / 'test/midpoint_cases.h'
    destination.write_text(generate(), encoding='utf-8', newline='\n')
