#!/usr/bin/env python3
"""Generate cached 5^q 128-bit table for chfloat.

It follows the published technique used by Eisel-Lemire style parsers:
- For q < 0: store ceil(2^b / 5^{-q}) ("inverse powers"), with b chosen to keep 128-bit.
- For q >= 0: store truncated 5^q scaled into [2^127, 2^128).

Outputs a C++ header with a single contiguous table for q in [-342, 308].
"""

from __future__ import annotations

import datetime

SMALLEST_Q = -342
LARGEST_Q = 308


def split_u128(x: int) -> tuple[int, int]:
    x &= (1 << 128) - 1
    hi = (x >> 64) & ((1 << 64) - 1)
    lo = x & ((1 << 64) - 1)
    return hi, lo


def gen() -> list[tuple[int, int]]:
    out: list[tuple[int, int]] = []

    # q in [-342, -1]
    for q in range(SMALLEST_Q, 0):
        power5 = 5 ** (-q)
        z = (power5.bit_length() - 1)
        if (1 << z) < power5:
            z += 1

        if q >= -27:
            b = z + 127
            c = (1 << b) // power5 + 1
        else:
            b = 2 * z + 2 * 64
            c = (1 << b) // power5 + 1
            # truncate to fit 128-bit
            while c >= (1 << 128):
                c >>= 1

        out.append(split_u128(c))

    # q in [0, 308]
    for q in range(0, LARGEST_Q + 1):
        power5 = 5 ** q
        # scale into [2^127, 2^128)
        while power5 < (1 << 127):
            power5 <<= 1
        while power5 >= (1 << 128):
            power5 >>= 1
        out.append(split_u128(power5))

    assert len(out) == (LARGEST_Q - SMALLEST_Q + 1)
    return out


def emit(header_path: str) -> None:
    table = gen()
    now = datetime.datetime.utcnow().strftime("%Y-%m-%d")

    with open(header_path, "w", encoding="utf-8", newline="\n") as f:
        f.write("#pragma once\n\n")
        f.write("// Generated by chfloat/script/gen_pow5_table.py on {} UTC\n".format(now))
        f.write("// Cached 128-bit representations of 5^q for q in [-342, 308].\n")
        f.write("// Table layout: entry i corresponds to q = smallest_q + i.\n\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace chfloat {\nnamespace detail {\n\n")
        f.write("struct alignas(16) pow5_128 { std::uint64_t hi; std::uint64_t lo; };\n\n")
        f.write("inline constexpr int pow5_smallest_q = {};\n".format(SMALLEST_Q))
        f.write("inline constexpr int pow5_largest_q = {};\n".format(LARGEST_Q))
        f.write("alignas(64) inline constexpr pow5_128 pow5_table[] = {\n")

        for (hi, lo) in table:
            f.write("  { 0x%016xULL, 0x%016xULL },\n" % (hi, lo))

        f.write("};\n\n")
        f.write("} // namespace detail\n} // namespace chfloat\n")


if __name__ == "__main__":
    emit("c:/CC/src/cf/chfloat/include/chfloat/detail/pow5_table.h")
